### ISSUE TITLE
Velocity stuck at 0.00 km/h on iDrive 7 DriveRecorder

### ISSUE THREAD

**Issue by bonsiapappel** [SkayoFox/BMW-driverecorder-processor#1]
Hi,

I've just found your tool, which is exactly what I was looking for. Great work. :-)
Only one thing seems to be odd when converting videos from iDrive 7 DriveRecorder - The Velocity is stuck at 0 km/h even if it is recorded in the Metafiles.
Maybe BMW changed the format for the Metafiles since you build this for iDrive 8?
I've attached a Metafile from from a video I've recorded today. Maybe this is somehow useful for you. Please let me know if I can provide more data. I'd be glad to support you with more informations to solve this issue.

[Metadata.json](https://github.com/SkayoFox/BMW-driverecorder-processor/files/15379420/Metadata.json)

Cheers, Volker

**Comment by SkayoFox** [comment]
Hi,

it's great to hear that you like my tool. Thank you very much :)
I actually don't own drive recorder anymore as I retrofitted a real dashcam to the car due to the low quality of the drive recorder. So I won't add new features for myself but I'm happy to so for others :)
So thanks for your report and the metadata file, I will fix that ASAP. It's an very easy fix. As you already thought, BMW changed to name of the speed parameter.

I'll let you know here when I found the time to fix this :)

**Comment by SkayoFox** [comment]
Whoops - I'm new to github :')

**Comment by SkayoFox** [comment]
I have a small question regarding the metadata. Do you know what unit "velocity" is? is it in km/h? mph? Or anything else?

**Comment by bonsiapappel** [comment]
Thanks for the reply - looking forward to the update! :-)

I took this record during a Driver Safety Training, and in this instance, the allowed top speed was 35 km/h. So, I'm pretty sure the velocity is set to km/h since this is the top value in the metadata. I guess in iDrive 7, the velocity is in the same unit as set in the iDrive settings.

Cheers, Volker

**Comment by SkayoFox** [comment]
Just fixed this in release v3.2 - I hope it works for you now :)

I'm closing this issue

**Comment by bonsiapappel** [comment]
I finally had the time to check out the new version. It works like a charm with iDrive 7 DriveRecorder. 

Thanks a lot! :-)
